version: "3.9"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - bodypace-mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bodypace_db

volumes:
  bodypace-mysql-volume:
